#!/usr/bin/env sh

FIFO=/run/minecraft/vertex.stdin

mkfifo -m 600 "$FIFO" 2>/dev/null || true
tail -f /dev/null > "$FIFO" &

exec java \
  -Xms4G -Xmx4G \
  -XX:+UseZGC -XX:+ZGenerational \
  -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions \
  -XX:+AlwaysPreTouch -XX:+DisableExplicitGC \
  -XX:+UseStringDeduplication -XX:+PerfDisableSharedMem \
  -XX:-DontCompileHugeMethods \
  -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 \
  -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M \
  -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M \
  -XX:NmethodSweepActivity=1 \
  --add-modules=jdk.incubator.vector \
  -Dpaper.preferSparkPlugin=true \
  -jar /srv/minecraft/vertex/purpur.jar nogui \
  < "$FIFO"
